project_id = "jxduytrjgxwdnwbkzhtu"

[functions.klaviyo-subscribe]
verify_jwt = false

[functions.klaviyo-create-lists]
verify_jwt = false

[functions.admin-cart-feedback]
verify_jwt = false

[functions.meta-capi-purchase]
verify_jwt = false
